### ISSUE TITLE
Support for Somfy RFS?

### ISSUE THREAD

**Issue by MacDennis76** [aequitas/python-rflink#2]
Hi @aequitas ,

At my home I have a sunscreen which is controlled by a Somfy motor, remote controlled. I can control it from the HomeWizard (433Mhz). When using Home Assistant I do not see any RF packages in the debug log.

When using the Rflink programmer & debugger on Windows I can see the 3 different packages being received by the RFLink device:

20;04;Debug;RTS P1;a7271126147907;
20;05;RTS;ID=147907;SWITCH=01;CMD=UP;

20;08;Debug;RTS P1;a81a1127147907;
20;09;RTS;ID=147907;SWITCH=01;CMD=STOP;

20;0C;Debug;RTS P1;a9411128147907;
20;0D;RTS;ID=147907;SWITCH=01;CMD=DOWN;

I ran your rflink python CLI tool on my NAS in verbose mode. It shows lots of sensors but the Somfy RF commands are not shown or detected.

What would be needed to support the Somfy RTS system? In the end I would like to control it with HASS.

Kind regards,
Dennis

**Comment by aequitas** [comment]
Commands should already be supported, only the CLI did not have them in the list of valid commands to print. Fixed in: https://github.com/aequitas/python-rflink/commit/dc872a972dff13d479615d45d30d6ea007bd3383

New package is being built. HASS support should be possible. But I have not spent time on it yet as I can't test blinds myself. If you open up an issue over there we can keep track of it and if you could help testing I can try and implement it.

**Comment by MacDennis76** [comment]
Thanks! Just created an issue:
https://github.com/home-assistant/home-assistant/issues/7583
Happy to help out.
