### ISSUE TITLE
Dropping invalid data on every boot of HA

### ISSUE THREAD

**Issue by sepodele** [aequitas/python-rflink#50]
On every boot of HA I get a warning saying "dropping invalid data: 20;01;MiLight=ON;". Can that be fixed?

**Comment by aequitas** [comment]
This is mostly due to there being incomplete data in the input buffer of the serial port when rflink first starts reading from the port. But it might also be legitimate invalid data coming in. You can change the loglevel in HA to only show errors and not warnings, as is described in the documentation on the HA website.
